name: "Send email after workflow"

on:
    workflow_dispatch: ## manually trigeering pipeline

jobs:
    send_email: # job name

        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"  # clone the code
              uses: actions/checkout@v4

            - name: "Setup Python environment" # setup python 3.x
              uses: actions/setup-python@v5
              with:
                python-version: '3.13' 

            - name: "Install Dependencies" # install pip for installing other dependencies
              run: |
                python -m pip install --upgrade pip

            - name: "Send email by executing python script"
              run: python script.py
              env:
                WORKFLOW_NAME: ${{github.workflow}} ## "github." context give info about repo
                REPO_NAME: ${{ github.repository}}
                WORKFLOW_RUN_ID: ${{github.run_id}}
                SENDER_PASSWORD: ${{secrets.SENDER_PASSWORD}} ## "secrets." context give info about repo secrets
                SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
                RECEIVER_EMAIL: ${{secrets.RECEIVER_EMAIL}}
                

